// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuhEslkHR00_RwPYUHwVzv-oJieRcGFqA',
    appId: '1:93234138483:web:ef027414f35633fbcec906',
    messagingSenderId: '93234138483',
    projectId: 'termproject-71613',
    authDomain: 'termproject-71613.firebaseapp.com',
    storageBucket: 'termproject-71613.firebasestorage.app',
    measurementId: 'G-WPBEHFPET4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC08zZThZy96k1-lOwzfw6yKRH-mUYC3U',
    appId: '1:93234138483:android:74612a3d0db3bc63cec906',
    messagingSenderId: '93234138483',
    projectId: 'termproject-71613',
    storageBucket: 'termproject-71613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTEP-lOk97Lq5R8S1OtE4BEP2jgzfpr_o',
    appId: '1:93234138483:ios:9cb817a0323d80f5cec906',
    messagingSenderId: '93234138483',
    projectId: 'termproject-71613',
    storageBucket: 'termproject-71613.firebasestorage.app',
    iosBundleId: 'com.example.uncwApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTEP-lOk97Lq5R8S1OtE4BEP2jgzfpr_o',
    appId: '1:93234138483:ios:9cb817a0323d80f5cec906',
    messagingSenderId: '93234138483',
    projectId: 'termproject-71613',
    storageBucket: 'termproject-71613.firebasestorage.app',
    iosBundleId: 'com.example.uncwApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuhEslkHR00_RwPYUHwVzv-oJieRcGFqA',
    appId: '1:93234138483:web:3cc98f5ddd7b7b78cec906',
    messagingSenderId: '93234138483',
    projectId: 'termproject-71613',
    authDomain: 'termproject-71613.firebaseapp.com',
    storageBucket: 'termproject-71613.firebasestorage.app',
    measurementId: 'G-HT8BX0Z8M7',
  );

}